FROM nvidia/cuda:12.0.0-devel-ubuntu22.04
RUN apt update && apt install -y \
    curl \
    linux-tools-5.15.0-86-generic \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
CMD ["bash"]